# Modules

import time
import os
import platform

# Clear Function

def clear():
    if platform.system() == 'Linux':
        os.system('clear')
    elif platform.system() == 'Windows':
        os.system('cls')

def p():
    os.system("pause >nul")

# Act 1 - Me and My Friends (Part I)

def actone():
    print("This act expects that you have finished 'Act 0 - Prologue'.")
    print("If you haven't yet finished 'Act 0 - Prologue', it is expected you finish it.")
    print("You may not understand the story if you do not finish the acts in order.")
    print("")
    print("Pressing a button will continue this act, or close this act if you haven't finished the aforementioned act(s). ⏎")

    p()
    clear()

    time.sleep(3)
    print("ACT 1 - ME AND MY FRIENDS (PART I)")
    time.sleep(1)
    print("BEGIN")
    time.sleep(3)
    clear()

    print("You:  Mom, I'm leaving for school! ⏎")
    p()
    print("Mom:  All the best, son! And when you are returning home, bring me some chocolate cookies, will you? ⏎")
    p()
    print("You:  Alright mom, bye! ⏎")
    p()
    print("Mom:  Bye Brendan! Love you! ⏎")
    p()
    print("You open the main gate, go out, and close it again. You walk to school. ⏎")
    p()
    print("You were walking when you notice one of your friends walking afar. ⏎")
    p()
    print("")
    clear()
    print("You:  Oh, hey there Ashley! ⏎")
    p()
    print("Ashley (Your friend):  Hello Brendan, how are you doing? ⏎")
    p()
    print("You:  I'm doing fine, what about you? ⏎")
    p()
    print("Ashley:  Hmm, I'm doing okay. ⏎")
    p()
    print("You:  Why do you look so sad? Is something wrong? ⏎")
    p()
    print("Ashley:  Can you just... not worry for a second? ⏎")
    p()
    print("Ashley:  Why do you always think that when anyone is silent they are sad? ⏎")
    p()
    print("You:  Hey, hey, no need to be rude! I was just worrying about you because- ")
    time.sleep(0.5)
    print("Ashley:  Yeah, then stop doing that! ⏎")
    p()
    print("Ashley:  I don't want you worrying about me, I can deal with things myself! ⏎")
    p()
    print("Ashley:  Bye! ⏎")
    p()
    print("You made Ashley angry... and she started to walk more speedily. ⏎")
    p()
    print("You:  Uhh... bye, I guess? ⏎")
    p()

    print("")
    print("???:  She is very self-contained, isn't she? ⏎")
    p()
    print("You look behind when you heard the voice, to see your best friend, Andrew. ⏎")
    p()
    print("You:  Haha, I wouldn't say self-contained. She just likes to be alone, I guess... ⏎")
    p()
    print("Andrew (Best Friend):  Hmm, I see. Anyways, how are you doing? ⏎")
    p()
    print("You:  Yeah, I am fine, and you? ⏎")
    p()
    print("Andrew: Cool as always bro! Let's hurry to school now! ⏎")
    p()
    print("You:  Sure!")
    p()
    clear()

    print("... ⏎")
    p()
    print("You are walking and walking... ⏎")
    p()
    print("... and walking... ⏎")
    p()
    print("... walking even more... ⏎")
    p()
    print("Andrew:  Watch out!!")
    time.sleep(0.5)
    clear()

    print("...")
    time.sleep(3)
    print("... ...")
    time.sleep(3)
    print("While you were walking on the street... you got hit by a truck.")
    time.sleep(3)
    print("... ...")
    time.sleep(3)
    print("You immediately blacked out.")
    time.sleep(3)
    print("Andrew and a few pedestrians carried you to the nearby hospital.")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("...")
    time.sleep(3)
    print("You didn't make it.")
    time.sleep(1)
    clear()

    time.sleep(3)
    print("GAME OVER")
    time.sleep(1)
    print("You died!")
    time.sleep(1)
    print("")
    print("Press any key to end the game. ⏎")
    p()
    clear()

    print("Exiting game in 5...")
    print("Thanks for playing this game.")
    time.sleep(5)
    clear()

    time.sleep(7)
    print("... ⏎")
    p()
    print("Character has been switched to Andrew. ⏎")
    p()
    print("You will play as Andrew from now on. ⏎")
    p()
    clear()

    time.sleep(3)
    print("ACT 1 - ME AND MY FRIENDS (PART I)")
    time.sleep(1)
    print("END")
    time.sleep(1)
    print("")
    print("To continue the story, please go into the 'Acts' folder and run 'acttwo.py'. Please press any key to exit.")
    p()
    exit()


actone()